[build]
publish = "public"
command = "make production-build"

[build.environment]
NODE_VERSION = "18.16.0"
HUGO_VERSION = "0.115.1"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

[[redirects]]
  from = "/about/governance"
  to = "https://github.com/opencontainers/tob/blob/main/CHARTER.md"
  status = 302
  force = false

[[redirects]]
  from = "chat.opencontainers.org"
  to = "https://join.slack.com/t/opencontainers/shared_invite/zt-1xbl5uuk1-V~YZNUtLfhCC5oucI9tnfA"
  status = 301
  force = false
